This is a meta-file about the general state of the project

* ToDo's
** TODO Set up wacom tablet bindings
*** TODO Set up file creation using nix home-manager
*** TODO Figure out what the bindings need to be
*** TODO Set up service to automattically start wacom binding on machine start up
- EXWM shell command ?
** TODO Create First/intro Blog for A weekly series
** TODO Create blog post about setting up a wacom tablet on nixos / Linux
** TODO Find new name for series

* Keybindings For Tablet Only Work Flow
** Upper Group
*** =(Ctrl-s)= Quick Save
**** =(Ctrl-Shft-s)= Save As
**** =(Ctrl-Alt-s)= Incremental Save
*** =PgDwn= Move Focus Down 1 Layer
**** =(PgDwn-Shft)= Move Focus Up 1 Layer
**** =(PgDwn-Ctrl)= Move Layer Down 1
**** =(PgDwn-Shft-Ctrl)= Move Layer Up1
*** =insert= Create and move to new Layer
**** =(Shft-Insert)= Create and move to new Vector Layer
**** =(Ctrl-Insert)= Delete currently active Layer
**** =(Alt-Insert)= Toggle Current Layer Visibility
*** =alt=
** Middle Key
*** =(Ctrl-z)= Undo
*** =(Ctrl-Shft-z)= Redo
*** =(Ctrl-Alt-z)= Reset Zoom
** Lower Group
*** =shft=
*** =ctrl=
*** =t= Move Tool
**** =(Ctrl-t)= Transform Tool
**** =(Shft-t)= Freehand Selection Tool
*** =b= Free Hand Brush Tool
**** =(Shft-b)= Contiguous Selection Tool
**** Bucket Tool
**** =(Ctrl-b)= Color Balance
** Pen
*** Point
**** =(Shft-Point)= Change Brush Size
**** =(Ctrl-Point)= Color Picker
*** Lower Button : =e= Grab Canvas
**** =(Shft-e)= Rotate Canvas
**** =(Ctrl-e)= Zoom Canvas
**** =(Alt-e)= Mirror Canvas
*** Upper Button : =(p)= Open Pop-Up Pallete
**** =(Shft-p)= Hide GUI
* Schedules
** 1
| Time     | A           | B           | C           | D           | E                     |
| 1/2 Hour | 1 Contour   | 25 Gesture  | 25 Gesture  | 25 Gesture  | 25 Gesture            |
| 1/2 Hour | 1 Contour   | 1 Contour   | 1 Contour   | 1 Contour   | 1 Sheet Cross Contour |
| 1/4 Hour | 1 Contour   | 15 Gesture  | 15 Gesture  | 15 Gesture  | 15 Gesture            |
| 1/4 Hour | Rest        | Rest        | Rest        | Rest        | Rest                  |
| 1/2 Hour | 1 Contour   | 25 Gesture  | 25 Gesture  | 25 Gesture  | 25 Gesture            |
| 1 Hour   | 1-2 Contour | 1-2 Contour | 1-2 Contour | 1-2 Contour | 1-2 Contour           |
- All exercises are drawings.
* Notes
** Week 1
*** Day 1
- Basic exercises went well. Need to add better exercises for straight lines, and pressure control
- First NWTD exerces went ok. Went to fast and looked at the canvas too much. Its really hard to stay focused on these exercises. They just feel extremely slow and draining to do.
- I am modifying the times for this first day. 20mins instead of 30, and 10mins instead of 15.
- Even with the shortened times. Fatigue is a real problem. Art quality is noticeably going down.
- Took a break to eat lunch before doing the last 3 problems. Lots of internal resistance to getting started again. I really don't enjoy these contour drawings. I feel like they just take so much slow deliberate focus, and it's mentally exhausting.
- Stopped after 5 drawings. I really don't like this style of practice. Luckily tomorrow uses gesture to break things up a lot.
*** Day 2
- Going to do 20 gestures, rather than 25. For easier integration with quickpose.
- Things went better today. The gesture drawings were less fatiguing. Still pretty much running out of gas by the end of the 3 hours.
*** Day 3
- Started about 20 minutes late, so I really pushed a fast pace for the warm up drills. I don't think in necessarily went badly. Back on track for the rest of the day.
- Getting some numbness in my arm. Probably over griping the pen. Glad I ordered the grip.
- Getting more comfortable with the contour drawings. Dropping them to 20 minutes and relaxing a bit more during the exercise made them much more palatable. Kind of focusing on the idea that something is better than nothing right now. It's only the first week.
- Still feeling exhausted by the end of the exercises. Skipped the last contour exercise. Looking forward to doing some more interesting drill.
*** Day 4
- First day using the new grip. Feels a bit awkward at the moment, but hopefully will improve with a bit of use.
- Still really not looking forward to these. They don't feel "fun", and there isn't really any visible progress.
- Also using the new titanium trip. I like it a lot, feels great.
*** Day 5
- Going to this week capstone as 5min gestures in various styles. I dont really feel comfortable with my current gesture technique. Too over simplified.
- Going to do the "page" of cross contour as 5-5minute drawings.
*** Capstone
- Multiple 5 minute Gestures in various styles
  - https://lundgrenart.weebly.com/uploads/3/8/0/6/38064807/5635_orig.jpg
  - https://i.pinimg.com/474x/90/be/7e/90be7efbf41861f7af6b1c3b01451ac0.jpg
  - Custom Gesture playlist
*** End of Week Summary
- Fatigue.
